name: qmap_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - pyyaml
  - python-dotenv
  - pip:
      - qiskit>=2.3.0
      - qiskit-ibm-runtime
      - qiskit-aer
      - qiskit-iqm
      - qiskit-ionq
      - iqm-client
      - qnexus
      - pytket-qiskit