host: ibm  # iqm , ibm, quantinuum, ionq
backend: ibm_pittsburgh  # qpu.aria-1, garnet:mock , ibm_boston, H1-Emulator, Helios-1E
env_path: tokens.env
reps: 20
minQubits:  4 #, 4
maxQubits:  8 #, 8
qubitStep:  2 #, 2
minShots: 1024  #, 1024
maxShots: 1024  #, 1024
shotStep: 0
